export const styles = {
  container: {
    position: 'relative' as const,
    width: '100%',
  },
  input: {
    width: '100%',
    padding: '0.875rem 1rem',
    borderRadius: '0.75rem',
    border: '1px solid rgba(0, 0, 0, 0.08)',
    background: '#fff',
    color: '#1a1a1a',
    boxShadow: '0 1px 2px rgba(0, 0, 0, 0.02)',
    outline: 'none',
    transition: 'all 0.2s ease',
    textAlign: 'left' as const,
    fontSize: '0.9375rem',
    lineHeight: '1.5',
  },
  inputFocus: {
    borderColor: 'rgba(0, 0, 0, 0.12)',
    boxShadow: '0 2px 4px rgba(0, 0, 0, 0.03)',
  },
  dropdown: {
    position: 'absolute' as const,
    zIndex: 50,
    marginTop: '0.125rem',
    width: '100%',
    borderRadius: '0.75rem',
    maxHeight: '15rem',
    overflowY: 'auto' as const,
    border: '1px solid rgba(0, 0, 0, 0.08)',
    background: '#fff',
    boxShadow: '0 4px 12px rgba(0, 0, 0, 0.05)',
    backdropFilter: 'blur(8px)',
  },
  noResults: {
    padding: '1rem',
    fontSize: '0.875rem',
    color: '#666',
    textAlign: 'left' as const,
  },
  option: {
    padding: '0.875rem 1rem',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    gap: '0.875rem',
    transition: 'all 0.15s ease',
    textAlign: 'left' as const,
  },
  optionHover: {
    background: 'rgba(0, 0, 0, 0.02)',
  },
  optionSelected: {
    background: 'rgba(0, 0, 0, 0.03)',
  },
  tokenImage: {
    width: '2.25rem',
    height: '2.25rem',
    borderRadius: '50%',
    flexShrink: 0,
    objectFit: 'cover' as const,
    border: '1px solid rgba(0, 0, 0, 0.06)',
  },
  tokenImageSelected: {
    border: '1.5px solid rgba(0, 0, 0, 0.1)',
  },
  tokenInfo: {
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'flex-start',
    minWidth: 0,
    width: '100%',
    gap: '0.25rem',
  },
  tokenName: {
    fontSize: '0.9375rem',
    fontWeight: 500,
    color: '#1a1a1a',
    width: '100%',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap' as const,
    textAlign: 'left' as const,
    lineHeight: '1.4',
  },
  tokenAddress: {
    fontSize: '0.75rem',
    color: '#666',
    width: '100%',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap' as const,
    textAlign: 'left' as const,
    fontFamily: 'monospace',
    letterSpacing: '-0.01em',
  },
}; 